---
name: Group

on:
    push:
    pull_request:

jobs:
    test_all:
        name: Tests Group
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v3
              with:
                java-version: '20'
                distribution: 'corretto'
            - run: gradle test

    build_all:
        name: Build Group
        runs-on: ubuntu-latest
        needs: 
            - test_all

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v3
              with:
                java-version: '20'
                distribution: 'corretto'
            - run: gradle build

# we want to run:
# checkstyle & pmd checks
# hadolint
